### ISSUE TITLE
工业表计读数例程运行出错

### ISSUE THREAD

**Issue by xs818818** [PaddlePaddle/tutorials#764]
我的版本是paddlex==1.3.11
报错
  File "/home/xs/.local/lib/python3.8/site-packages/paddlex/cv/models/load_model.py", line 43, in load_model
    raise Exception("There's no attribute {} in paddlex.cv.models".format(
Exception: There's no attribute PPYOLOv2 in paddlex.cv.models
后尝试用2.0.0
报错
  if data.dtype == np.object:
Your running script needs PaddleX<2.0.0, please refer to https://github.com/PaddlePaddle/PaddleX/tree/release/2.0-rc/tutorials/train#%E7%89%88%E6%9C%AC%E5%8D%87%E7%BA%A7 to solve this issue.

**Comment by emptystack1024** [comment]
你是如何解决这个问题的呢
